### PR TITLE
1.4.1 branch

### PR DESCRIPTION
**Pull request by markdelf**
IP Validation fixes for older PHP. Before we deploy this fix we need to remove the INI setting in the constructor.

### CODE REVIEW

**Comment by markdelf** [comment]
@carmelopreeostudios please remove the ini in the constructor of 1.4.1-branch before we accept the pull request. We do not want to switch on debug for everyone.

@robert81 take note.

**Comment by robert81** [comment]
Yes correct, forgot about that. @carmelopreeostudios Can we please take
care of it this morning so we release it today?

Thank you.

On 12 March 2015 at 06:27, Mark Camilleri <notifications@github.com> wrote:

> @carmelopreeostudios <https://github.com/carmelopreeostudios> please
> remove the ini in the constructor of 1.4.1-branch before we accept the pull
> request. We do not want to switch on debug for everyone.
>
> @robert81 <https://github.com/robert81> take note.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WPWhiteSecurity/WP-Security-Audit-Log/pull/48#issuecomment-78425974>
> .
>



-- 
Regards,
Robert Abela
e: abela.robert@gmail.com
m: +356 99885541

**Comment by joseforland** [comment]
@robert81 ini_set removed & merge request done

**Comment by robert81** [comment]
Thanks a lot. Will release then.


On 12 March 2015 at 09:12, joseforland <notifications@github.com> wrote:

> @robert81 <https://github.com/robert81> ini_set removed & merge request
> done
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WPWhiteSecurity/WP-Security-Audit-Log/pull/48#issuecomment-78438721>
> .
>



-- 
Regards,
Robert Abela
e: abela.robert@gmail.com
m: +356 99885541

**Pull request merged**
